# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tika_file_extract.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tika_file_extract.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17tika_file_extract.proto\"#\n\x0fTikaFileExtract\x12\x10\n\x08\x66ilename\x18\x01 \x02(\t\"[\n\x15TikaFileExtractResult\x12\x10\n\x08\x66ilename\x18\x01 \x02(\t\x12\x0c\n\x04path\x18\x02 \x02(\t\x12\x11\n\tmime_type\x18\x03 \x02(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x02(\t\"D\n\x19ListTikaFileExtractResult\x12\'\n\x07results\x18\x01 \x03(\x0b\x32\x16.TikaFileExtractResult'
)




_TIKAFILEEXTRACT = _descriptor.Descriptor(
  name='TikaFileExtract',
  full_name='TikaFileExtract',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='TikaFileExtract.filename', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=62,
)


_TIKAFILEEXTRACTRESULT = _descriptor.Descriptor(
  name='TikaFileExtractResult',
  full_name='TikaFileExtractResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='TikaFileExtractResult.filename', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='path', full_name='TikaFileExtractResult.path', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mime_type', full_name='TikaFileExtractResult.mime_type', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='TikaFileExtractResult.content', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=155,
)


_LISTTIKAFILEEXTRACTRESULT = _descriptor.Descriptor(
  name='ListTikaFileExtractResult',
  full_name='ListTikaFileExtractResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='ListTikaFileExtractResult.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=225,
)

_LISTTIKAFILEEXTRACTRESULT.fields_by_name['results'].message_type = _TIKAFILEEXTRACTRESULT
DESCRIPTOR.message_types_by_name['TikaFileExtract'] = _TIKAFILEEXTRACT
DESCRIPTOR.message_types_by_name['TikaFileExtractResult'] = _TIKAFILEEXTRACTRESULT
DESCRIPTOR.message_types_by_name['ListTikaFileExtractResult'] = _LISTTIKAFILEEXTRACTRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TikaFileExtract = _reflection.GeneratedProtocolMessageType('TikaFileExtract', (_message.Message,), {
  'DESCRIPTOR' : _TIKAFILEEXTRACT,
  '__module__' : 'tika_file_extract_pb2'
  # @@protoc_insertion_point(class_scope:TikaFileExtract)
  })
_sym_db.RegisterMessage(TikaFileExtract)

TikaFileExtractResult = _reflection.GeneratedProtocolMessageType('TikaFileExtractResult', (_message.Message,), {
  'DESCRIPTOR' : _TIKAFILEEXTRACTRESULT,
  '__module__' : 'tika_file_extract_pb2'
  # @@protoc_insertion_point(class_scope:TikaFileExtractResult)
  })
_sym_db.RegisterMessage(TikaFileExtractResult)

ListTikaFileExtractResult = _reflection.GeneratedProtocolMessageType('ListTikaFileExtractResult', (_message.Message,), {
  'DESCRIPTOR' : _LISTTIKAFILEEXTRACTRESULT,
  '__module__' : 'tika_file_extract_pb2'
  # @@protoc_insertion_point(class_scope:ListTikaFileExtractResult)
  })
_sym_db.RegisterMessage(ListTikaFileExtractResult)


# @@protoc_insertion_point(module_scope)
