# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tika_file_extract_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'tika_file_extract_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tika_file_extract_pb2 as tika__file__extract__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ftika_file_extract_service.proto\x1a\x17tika_file_extract.proto2\xc9\x02\n\x11TikaFileExtractor\x12\x41\n\x0f\x45xtractFromFile\x12\x10.TikaFileExtract\x1a\x1a.ListTikaFileExtractResult\"\x00\x12O\n\x1b\x45xtractFromFileClientStream\x12\x10.TikaFileExtract\x1a\x1a.ListTikaFileExtractResult\"\x00(\x01\x12O\n\x1b\x45xtractFromFileServerStream\x12\x10.TikaFileExtract\x1a\x1a.ListTikaFileExtractResult\"\x00\x30\x01\x12O\n\x19\x45xtractFromFileBothStream\x12\x10.TikaFileExtract\x1a\x1a.ListTikaFileExtractResult\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tika_file_extract_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIKAFILEEXTRACTOR']._serialized_start=61
  _globals['_TIKAFILEEXTRACTOR']._serialized_end=390
# @@protoc_insertion_point(module_scope)
